<a href="https://colab.research.google.com/github/KhamidjonovRakhmatullo/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
print(pd.__version__)

2.2.2

In [ ]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Damas", "Bugatti"],
  'counts': [3, 7, 2, 8, 1, 9, 3]
}

df = pd.DataFrame(mydataset)

print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5    Damas       9
6  Bugatti       3

In [ ]:
# cars and counts  -> column labels / column names
# 0, 1, 2, 3...    -> row labels / row indexes

In [ ]:
# ------------------------------ head() ------------------------------

# head() -> dataset boshidagi qatorlarni ko‘rsatadi


# 1) Default holatda birinchi 5 ta qatorni chiqarish

df.head()
# birinchi 5 ta row chiqadi


# ---------------------------------------------------------------------

# 2) Birinchi 10 ta qatorni chiqarish

# df.head(10)
# birinchi 10 ta row chiqadi


# ---------------------------------------------------------------------

# 3) Oxirgi 1 ta qatordan tashqari hammasini chiqarish

# df.head(-1)
# oxirgi 1 ta row chiqmaydi


# ---------------------------------------------------------------------

# 4) Faqat column nomlarini chiqarish

# df.head(0)
# data row chiqmaydi, faqat column nomlari chiqadi


# ---------------------------------------------------------------------

# Simple meaning:

# head()    -> first 5 rows
# head(10)  -> first 10 rows
# head(-1)  -> all rows except last 1 row
# head(0)   -> only column names

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1

In [ ]:
# ------------------------------ tail() ------------------------------

# tail() -> dataset oxiridagi qatorlarni ko‘rsatadi


# 1) Default holatda oxirgi 5 ta qatorni chiqarish

df.tail()
# oxirgi 5 ta row chiqadi


# ---------------------------------------------------------------------

# 2) Oxirgi 10 ta qatorni chiqarish

# df.tail(10)
# oxirgi 10 ta row chiqadi


# ---------------------------------------------------------------------

# 3) Birinchi 1 ta qatordan tashqari hammasini chiqarish

# df.tail(-1)
# birinchi 1 ta row chiqmaydi


# ---------------------------------------------------------------------

# 4) Faqat column nomlarini chiqarish

# df.tail(0)
# data row chiqmaydi, faqat column nomlari chiqadi


# ---------------------------------------------------------------------

# Simple meaning:

# tail()    -> last 5 rows
# tail(10)  -> last 10 rows
# tail(-1)  -> all rows except first 1 row
# tail(0)   -> only column names

      cars  counts
2     Ford       2
3    Tesla       8
4  Ferrari       1
5    Damas       9
6  Bugatti       3

In [ ]:
# ------------------------------ shape ------------------------------

# df.shape -> dataset nechta row va column borligini ko‘rsatadi

df.shape
# (row_count, column_count)

(7, 2)

In [ ]:
# ------------------------------ columns ------------------------------

# columns -> datasetdagi barcha column nomlarini ko‘rsatadi


# 1) Column nomlarini ko‘rish

df.columns
# Index(['cars', 'counts'], dtype='object')


# ---------------------------------------------------------------------

# 2) Column nomlarini Python list ko‘rinishida chiqarish

# list(df.columns)
# ['cars', 'counts']


# ---------------------------------------------------------------------

# Simple meaning:

# df.columns       -> column nomlarini Index ko‘rinishida chiqaradi
# list(df.columns) -> column nomlarini oddiy list ko‘rinishida chiqaradi

Index(['cars', 'counts'], dtype='object')

In [ ]:
# ------------------------------ dtypes ------------------------------

# dtypes -> har bir column'ning data type'ini ko‘rsatadi


# 1) Barcha column'larning data type'larini ko‘rish

df.dtypes
# cars      object
# counts     int64
# dtype: object


# ---------------------------------------------------------------------

# 2) Bitta column'ning data type'ini ko‘rish

# df["cars"].dtype
# object


# df["counts"].dtype
# int64


# ---------------------------------------------------------------------

# Simple meaning:

# df.dtypes          -> barcha column type'larini chiqaradi
# df["cars"].dtype   -> faqat cars column type'ini chiqaradi
# df["counts"].dtype -> faqat counts column type'ini chiqaradi

cars      object
counts     int64
dtype: object

In [ ]:
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5    Damas       9
6  Bugatti       3

In [ ]:
# ------------------------------ describe() ------------------------------

# describe() -> numeric column'lar bo‘yicha statistik ma’lumot chiqaradi


# 1) Numeric column'lar uchun statistik ma’lumot ko‘rish

df.describe()
# count, mean, std, min, max kabi qiymatlarni ko‘rsatadi


# ---------------------------------------------------------------------

# describe() ichidagi qiymatlar:

# count -> nechta qiymat bor
# mean  -> o‘rtacha qiymat
# std   -> standard deviation, qiymatlar qanchalik tarqalganini ko‘rsatadi
# min   -> eng kichik qiymat
# 25%   -> 1-chorak qiymat
# 50%   -> median, o‘rtadagi qiymat
# 75%   -> 3-chorak qiymat
# max   -> eng katta qiymat


# ---------------------------------------------------------------------

# 2) Barcha column'lar uchun describe ko‘rish

# df.describe(include="all")
# numeric + text column'larni ham ko‘rsatadi


# ---------------------------------------------------------------------

# Simple meaning:

# df.describe()              -> numeric column'larni tahlil qiladi
# df.describe(include="all") -> barcha column'larni tahlil qiladi

         counts
count  7.000000
mean   4.714286
std    3.199702
min    1.000000
25%    2.500000
50%    3.000000
75%    7.500000
max    9.000000

In [ ]:
# ------------------------------ iloc ------------------------------

# iloc -> row va column'larni index raqami orqali tanlaydi
# iloc = integer location


# 1) Birinchi row'ni chiqarish

df.iloc[0]
# birinchi row chiqadi


# ---------------------------------------------------------------------

# 2) Birinchi 5 ta row'ni chiqarish

# df.iloc[0:5]
# 0-indexdan 5-indexgacha chiqaradi
# 5-index kirmaydi


# ---------------------------------------------------------------------

# 3) 0-indexdan tashqari hamma row'ni chiqarish

# df.iloc[1:]
# 1-indexdan boshlab oxirigacha chiqaradi


# ---------------------------------------------------------------------

# 4) Bitta qiymatni olish

# df.iloc[0, 1]
# 0-indexdagi row va 1-indexdagi column qiymatini chiqaradi


# ---------------------------------------------------------------------

# 5) Faqat birinchi column'ni chiqarish

# df.iloc[:, 0]
# barcha row'lar, faqat 0-indexdagi column chiqadi


# ---------------------------------------------------------------------

# 6) Birinchi 5 ta row va birinchi 2 ta column'ni chiqarish

# df.iloc[0:5, 0:2]
# 0 dan 5 gacha row, 0 dan 2 gacha column
# 5 va 2 kirmaydi


# ---------------------------------------------------------------------

# 7) Oxirgi row'ni chiqarish

# df.iloc[-1]
# oxirgi row chiqadi


# ---------------------------------------------------------------------

# Simple meaning:

# df.iloc[0]          -> first row
# df.iloc[0:5]        -> first 5 rows
# df.iloc[1:]         -> all rows except first row
# df.iloc[0, 1]       -> row 0, column 1 value
# df.iloc[:, 0]       -> first column
# df.iloc[0:5, 0:2]   -> first 5 rows and first 2 columns
# df.iloc[-1]         -> last row

cars      BMW
counts      3
Name: 0, dtype: object

In [ ]:
# ------------------------------ loc ------------------------------

# loc -> row va column'larni label/name orqali tanlaydi
# loc = label location


# 1) Index label'i 0 bo‘lgan row'ni chiqarish

df.loc[0]
# BMW, 3


# ---------------------------------------------------------------------

# 2) 0 dan 3 gacha bo‘lgan row'larni chiqarish

# df.loc[0:3]
# loc’da 3 ham kiradi


# ---------------------------------------------------------------------

# 3) Bitta qiymatni olish: cars column

# df.loc[0, "cars"]
# 0-indexdagi "cars" qiymatini chiqaradi
# BMW


# ---------------------------------------------------------------------

# 4) Bitta qiymatni olish: counts column

# df.loc[0, "counts"]
# 0-indexdagi "counts" qiymatini chiqaradi
# 3


# ---------------------------------------------------------------------

# 5) Faqat cars column'ini chiqarish

# df.loc[:, "cars"]
# barcha row'lar, faqat cars column chiqadi


# ---------------------------------------------------------------------

# 6) Cars va counts column'larini chiqarish

# df.loc[:, ["cars", "counts"]]
# barcha row'lar, cars va counts column'lari chiqadi


# ---------------------------------------------------------------------

# 7) 0 dan 4 gacha row va kerakli column'larni chiqarish

# df.loc[0:4, ["cars", "counts"]]
# 0 dan 4 gacha row'lar, cars va counts column'lari
# loc’da 4 ham kiradi


# ---------------------------------------------------------------------

# 8) Condition bilan filter qilish

# df.loc[df["counts"] > 5]
# counts 5 dan katta bo‘lgan row'larni chiqaradi
# Volvo, Tesla, Damas


# ---------------------------------------------------------------------

# 9) Text qiymat bo‘yicha filter qilish

# df.loc[df["cars"] == "Tesla"]
# cars Tesla bo‘lgan row'ni chiqaradi


# ---------------------------------------------------------------------

# 10) Aniq qiymat bo‘yicha filter qilish

# df.loc[df["counts"] == 3]
# counts 3 ga teng bo‘lgan row'larni chiqaradi
# BMW, Bugatti


# ---------------------------------------------------------------------

# Simple meaning:

# df.loc[0]                         -> index label 0 row
# df.loc[0:3]                       -> row 0 dan 3 gacha
# df.loc[0, "cars"]                 -> row 0, cars value
# df.loc[:, "cars"]                 -> faqat cars column
# df.loc[:, ["cars", "counts"]]     -> cars va counts columns
# df.loc[df["counts"] > 5]          -> condition bilan filter
# df.loc[df["cars"] == "Tesla"]     -> Tesla row'ni topish

cars      BMW
counts      3
Name: 0, dtype: object

In [ ]:
df[df["counts"] > 5]
df[df["cars"] == "Tesla"]

    cars  counts
3  Tesla       8

In [ ]:
# ------------------------------ math methods ------------------------------

# Math methods -> numeric qiymatlar ustida hisob-kitob qiladi


# ---------------------------------------------------------------------
# 1) One selected column
# ---------------------------------------------------------------------

# mean() -> o‘rtacha qiymatni chiqaradi

df["counts"].mean()

# ---

# median() -> o‘rtadagi qiymatni chiqaradi

# df["counts"].median()

# ---

# sum() -> qiymatlarni qo‘shadi

# df["counts"].sum()

# ---

# min() -> eng kichik qiymatni chiqaradi

# df["counts"].min()

# ---

# max() -> eng katta qiymatni chiqaradi

# df["counts"].max()


# ---------------------------------------------------------------------
# 2) All numeric columns
# ---------------------------------------------------------------------

# numeric_only=True -> faqat number column'lar bilan ishlaydi

# df.mean(numeric_only=True)
# df.median(numeric_only=True)
# df.sum(numeric_only=True)
# df.min(numeric_only=True)
# df.max(numeric_only=True)


# ---------------------------------------------------------------------
# Simple meaning:
# ---------------------------------------------------------------------

# df["counts"].mean()        -> faqat counts column uchun
# df.mean(numeric_only=True) -> barcha numeric column'lar uchun

# mean()   -> o‘rtacha qiymat
# median() -> o‘rtadagi qiymat
# sum()    -> jami yig‘indi
# min()    -> eng kichik qiymat
# max()    -> eng katta qiymat

cars      7
counts    7
dtype: int64

In [ ]:
# ------------------------------ count() ------------------------------

# count() -> empty bo‘lmagan qiymatlarni sanaydi
# NaN / None qiymatlarni hisoblamaydi


# ---------------------------------------------------------------------
# 1) One selected column
# ---------------------------------------------------------------------

df["counts"].count()
# counts column'ida nechta empty bo‘lmagan qiymat borligini chiqaradi


# ---------------------------------------------------------------------
# 2) All columns
# ---------------------------------------------------------------------

# df.count()
# har bir column uchun empty bo‘lmagan qiymatlar sonini chiqaradi


# ---------------------------------------------------------------------
# Simple meaning:
# ---------------------------------------------------------------------

# df["counts"].count() -> faqat counts column uchun sanaydi
# df.count()           -> barcha column'lar uchun sanaydi

cars      7
counts    7
dtype: int64

In [ ]:
# ------------------------------ std() ------------------------------

# std() -> qiymatlar o‘rtachadan qanchalik tarqalganini ko‘rsatadi
# std = standard deviation


# ---------------------------------------------------------------------
# 1) One selected column
# ---------------------------------------------------------------------

# df["counts"].std()
# counts column'i uchun standard deviation chiqaradi


# ---------------------------------------------------------------------
# 2) All numeric columns
# ---------------------------------------------------------------------

df.std(numeric_only=True)
# barcha numeric column'lar uchun standard deviation chiqaradi


# ---------------------------------------------------------------------
# Simple meaning:
# ---------------------------------------------------------------------

# std kichik bo‘lsa -> qiymatlar bir-biriga yaqin
# std katta bo‘lsa  -> qiymatlar ko‘proq tarqalgan

counts    3.199702
dtype: float64

In [ ]:
# Missing value bor dataset yaratamiz

data_with_missing = {
  'cars': ["BMW", "Volvo", None, "Tesla", "Ferrari", None, "Bugatti"],
  'counts': [3, 7, None, 8, 1, 3, None]
}

df_missing = pd.DataFrame(data_with_missing)

print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     8.0
4  Ferrari     1.0
5     None     3.0
6  Bugatti     NaN

In [ ]:
# ------------------------------ isnull() ------------------------------

# isnull() -> missing value bor joylarni True/False qilib ko‘rsatadi


# 1) Missing value bor joylarni ko‘rish

df_missing.isnull()
# True  -> missing value bor
# False -> missing value yo‘q


# ---------------------------------------------------------------------

# 2) Har bir column'da nechta missing value borligini sanash

# df_missing.isnull().sum()
# cars va counts column'larida nechta NaN/None borligini chiqaradi


# ---------------------------------------------------------------------

# 3) Umumiy nechta missing value borligini sanash

# df_missing.isnull().sum().sum()
# butun DataFrame ichidagi jami missing value sonini chiqaradi


# ---------------------------------------------------------------------

# 4) Bitta column bo‘yicha missing value tekshirish

# df_missing["cars"].isnull()
# faqat cars column'idagi missing joylarni ko‘rsatadi


# df_missing["counts"].isnull()
# faqat counts column'idagi missing joylarni ko‘rsatadi


# ---------------------------------------------------------------------

# 5) Missing value bor row'larni chiqarish

# df_missing[df_missing["cars"].isnull()]
# cars column'ida missing value bor row'larni chiqaradi


# df_missing[df_missing["counts"].isnull()]
# counts column'ida missing value bor row'larni chiqaradi


# ---------------------------------------------------------------------

# Simple meaning:

# isnull()              -> missing joylarni True/False qiladi
# isnull().sum()        -> har bir column'dagi missing sonini chiqaradi
# isnull().sum().sum()  -> jami missing value sonini chiqaradi

    cars  counts
0  False   False
1  False   False
2   True    True
3  False   False
4  False   False
5   True   False
6  False    True

In [ ]:
# ------------------------------ dropna() ------------------------------

# dropna() -> missing value bor row'larni olib tashlaydi

# ---------------------------------------------------------------------

# 1) Missing value bor row'larni olib tashlash

df_missing.dropna()
# bitta NaN/None bo‘lsa ham o‘sha row o‘chadi


# ---------------------------------------------------------------------

# 2) Faqat hamma qiymatlari missing bo‘lgan row'larni olib tashlash

# df_missing.dropna(how="all")
# row ichidagi barcha column'lar NaN/None bo‘lsa, o‘sha row o‘chadi


# ---------------------------------------------------------------------

# 3) Missing value bor column'larni olib tashlash

# df_missing.dropna(axis=1)
# qaysi column'da NaN/None bo‘lsa, o‘sha column o‘chadi


# ---------------------------------------------------------------------

# 4) Faqat bitta column bo‘yicha tekshirish

# df_missing.dropna(subset=["cars"])
# cars column'ida missing value bor row'larni o‘chiradi


# df_missing.dropna(subset=["counts"])
# counts column'ida missing value bor row'larni o‘chiradi


# ---------------------------------------------------------------------

# 5) inplace=True -> original DataFrame'ni o‘zgartiradi

# df_missing.dropna(inplace=True)
# natija yangi variable'ga saqlanmaydi, df_missing o‘zi o‘zgaradi


# ---------------------------------------------------------------------

# Simple meaning:

# dropna()                 -> missing bor row'larni o‘chiradi
# dropna(how="all")        -> hammasi missing bo‘lgan row'ni o‘chiradi
# dropna(axis=1)           -> missing bor column'larni o‘chiradi
# dropna(subset=["cars"])  -> faqat cars column bo‘yicha tekshiradi
# inplace=True             -> result'ni original DataFrame'ga saqlaydi

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0

In [ ]:
# ------------------------------ fillna() ------------------------------

# fillna() -> missing value'larni boshqa qiymat bilan to‘ldiradi

# ---------------------------------------------------------------------

# 1) Barcha missing value'larni bitta qiymat bilan to‘ldirish

df_missing.fillna("Unknown")
# barcha NaN/None qiymatlarni "Unknown" bilan to‘ldiradi


# ---------------------------------------------------------------------

# 2) Har xil column'larni har xil qiymat bilan to‘ldirish

# df_missing.fillna({
#     "cars": "Unknown",
#     "counts": 0
# })

# cars   -> None qiymatlar "Unknown" bo‘ladi
# counts -> NaN qiymatlar 0 bo‘ladi


# ---------------------------------------------------------------------

# 3) Faqat bitta column bo‘yicha to‘ldirish

# df_missing["cars"].fillna("Unknown")
# cars column'dagi missing qiymatlarni "Unknown" qiladi


# df_missing["counts"].fillna(0)
# counts column'dagi missing qiymatlarni 0 qiladi


# ---------------------------------------------------------------------

# 4) Mean bilan to‘ldirish

# df_missing["counts"].fillna(df_missing["counts"].mean())
# counts column'dagi missing qiymatlarni o‘rtacha qiymat bilan to‘ldiradi


# ---------------------------------------------------------------------

# 5) inplace=True -> original DataFrame'ni o‘zgartiradi

# df_missing.fillna({
#     "cars": "Unknown",
#     "counts": 0
# }, inplace=True)


# ---------------------------------------------------------------------

# Simple meaning:

# fillna("Unknown") -> missing joylarni "Unknown" bilan to‘ldiradi
# fillna(0)         -> missing joylarni 0 bilan to‘ldiradi
# fillna(mean)      -> missing joylarni o‘rtacha qiymat bilan to‘ldiradi
# inplace=True      -> result'ni original DataFrame'ga saqlaydi

      cars   counts
0      BMW      3.0
1    Volvo      7.0
2  Unknown  Unknown
3    Tesla      8.0
4  Ferrari      1.0
5  Unknown      3.0
6  Bugatti  Unknown

In [127]:
# ------------------------------ read files ------------------------------

df = pd.read_csv("Titanic-Dataset.csv")

df.head(2)

# df = pd.read_excel("Titanic-Dataset.xlsx")
# df = pd.json("Titanic-Dataset.json")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [129]:
# ------------------------------ export file ------------------------------

df.to_excel("output.xlsx")

In [136]:
# ------------------------------ Series => 1D ------------------------------

cars = pd.Series(["BMW", "Tesla", "Ferrari"])

print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [139]:
# ------------------------------ Series => 2D ------------------------------

data_set = {
  'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Damas", "Bugatti"],
  'counts': [3, 7, 2, 8, 1, 9, 3]
}

data_series = pd.Series(data_set)

cars_series = data_series["cars"]

print(cars_series)

['BMW', 'Volvo', 'Ford', 'Tesla', 'Ferrari', 'Damas', 'Bugatti']